
testFunctor.exe:  testFunctor.o
	g++  testFunctor.cpp -o testFunctor.exe

#optim.o: ./headerFiles/optim.cpp
#	g++ -c ./headerFiles/optim.cpp

# 
testFunctor.o: testFunctor.cpp  ./headerFiles/C2R.h ./headerFiles/Functor.h ./headerFiles/CRn.h ./headerFiles/GBM.h
	g++ -c testFunctor.cpp


#testOptim.exe:  testOptim.o
#	g++  testOptim.cpp -o testOptim.exe

#optim.o: ./headerFiles/optim.cpp
#	g++ -c ./headerFiles/optim.cpp

# 
#testOptim.o: testOptim.cpp ./headerFiles/optim.h ./headerFiles/function.h ./headerFiles/functor1.h 
	#g++ -c testOptim.cpp

#clear:
	#rm *.o testOptim.exe
